AllCops:
  TargetRubyVersion: 2.6.5
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'